In [2]:
import sys
sys.path.append('..') 
from src.data_loader import load_data

In [3]:
df = load_data()

In [4]:
df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,BF9B45EF846F766F,electric_bike,2025-04-05 15:18:25.360,2025-04-05 15:32:07.818,111 St & 53 Ave,6171.02,Broadway & 74 St,6332.10,40.743360,-73.851290,40.746530,-73.891210,casual
1,019D3C58B9CCA0AD,electric_bike,2025-04-02 08:58:40.957,2025-04-02 09:04:59.729,E 27 St & 1 Ave,6004.06,E 40 St & Park Ave,6432.11,40.739445,-73.976806,40.750756,-73.978326,member
2,5E68E6942DE381BD,classic_bike,2025-04-08 11:58:27.583,2025-04-08 12:06:55.120,W 113 St & Broadway,7713.01,Frederick Douglass Blvd & W 117 St,7688.12,40.805973,-73.964928,40.805159,-73.954692,member
3,801EAB661E50A4C1,electric_bike,2025-04-01 09:48:58.509,2025-04-01 09:53:00.136,Lexington Ave & E 26 St,6089.08,E 40 St & Park Ave,6432.11,40.741459,-73.983293,40.750756,-73.978326,member
4,ED609B115FB559EC,electric_bike,2025-04-09 11:15:45.418,2025-04-09 11:25:51.783,Bedford Park Blvd & Paul Ave,8752.01,Jerome Ave & E Mosholu Pkwy S,8795.01,40.874440,-73.891860,40.879350,-73.885340,member

In [6]:
df.describe()

          start_lat     start_lng       end_lat       end_lng
count  2.819422e+07  2.819422e+07  2.812105e+07  2.812105e+07
mean   4.073672e+01 -7.397170e+01  4.073654e+01 -7.397178e+01
std    4.040610e-02  2.889403e-02  4.316914e-02  4.018186e-02
min    4.063338e+01 -7.403699e+01  0.000000e+00 -7.408670e+01
25%    4.071255e+01 -7.399209e+01  4.071255e+01 -7.399233e+01
50%    4.073535e+01 -7.397907e+01  4.073524e+01 -7.397907e+01
75%    4.076018e+01 -7.395509e+01  4.076009e+01 -7.395516e+01
max    4.088630e+01 -7.384672e+01  4.088630e+01  0.000000e+00